website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

# models = Blueprint('models', __name__)
class User(db.Model, UserMixin):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key=True)
	email = db.Column(db.String(100), unique=True)
	username = db.Column(db.String(100))
	password = db.Column(db.String(100))
	notes = db.relationship('Note')

class Note(db.Model):
	__tablename__ = 'notes'
	id = db.Column(db.Integer, primary_key=True)
	data = db.Column(db.String(10000))
	date = db.Column(db.DateTime(timezone=True), default=func.now())
	user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_admin import Admin
from flask_admin.contrib.sqla import ModelView 
from os import path

db = SQLAlchemy()
admin = Admin(name='Notes App Admin Panel', template_mode='bootstrap3')
db_name = 'database.db'


def create_app():
	# initialize your flask app
	app = Flask(__name__)
	app.config['SECRET_KEY'] = 'Th3N@rThR3meMBers'	# set up secret key to encrypt & secure our cookie sessions
	app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{db_name}'
	# themes = 'cerulean', 'cosmo', 'cyborg', 'flatly', 'darkly'
	app.config['FLASK_ADMIN_SWATCH'] = 'flatly'	#set bootswatch theme
	db.init_app(app)	#initialize our database
	admin.init_app(app)	#instatiate our admin panel


	# import the different blueprints and register them
	from .views import views
	app.register_blueprint(views, url_prefix='/')
	from .auth import auth
	app.register_blueprint(auth, url_prefix='/')

	from .models import User, Note
	create_database(app)

	# build the admin panel
	# admin.add_view(ModelView(User, db.session,category='user'))
	admin.add_view(ModelView(User, db.session))
	admin.add_view(ModelView(Note, db.session))
	

	# handling login sessions
	login_manager = LoginManager()
	login_manager.login_view = 'auth.login'
	login_manager.init_app(app)

	@login_manager.user_loader
	def load_user(id):
		return User.query.get(int(id))	#automatically looks for the primary key column

	return app

def create_database(app):
	with app.app_context():
		if not path.exists('website/' + db_name):
			# db.create_all(app=app)
			db.create_all()
			print('Created database')
		else:
			print('database already exists')

website/auth.py
from flask import Blueprint,render_template, request,flash, redirect, url_for
from .models import User, Note
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user
from . import db
import json


auth = Blueprint('auth', __name__)



@auth.route('login', methods=['GET','POST'])
def login():
	if request.method == 'POST':
		email = request.form.get('email')
		password = request.form.get('password')

		user = User.query.filter_by(email=email).first()
		# if email is already in the database
		if user:
			# if password entered matches passoword in the database 
			if check_password_hash(user.password, password):
				message = 'Logged in succesfully!'
				flash(message, category='success')
				login_user(user, remember=True)
				return redirect(url_for('views.home'))
			# if password entered does not match passoword in the database 
			elif not check_password_hash(user.password, password):
				message = 'Password entered is incorrect'
				flash(message, category='error')

		# else they should signup
	# message = 'You do not have an account. Try signing up instead'
	# flash(message, category='success')

	return render_template('login.html', user=current_user)

@auth.route('sign-up', methods=['GET','POST'])
def signup():
	# ensure your signing in
	if request.method == 'POST':
		# get info from the form
		email = request.form.get('email')
		username = request.form.get('username')
		password = request.form.get('password')
		password2 = request.form.get('password2')

		user = User.query.filter_by(email=email).first()
		# validate info from the form
		if user:
			message = 'User already exists!'
			flash(message, category='error')
		elif len(email) < 10 or len(username) < 1:
			message1 = 'email address'
			message2 = 'username'
			flash(f'You either entered an invalid {message1} or {message2}', category='error')
		elif len(password) < 4 or password != password2:
			message1 = 'too short'
			message2 = 'they do not match'
			flash(f'Your password information is either {message1} or {message2}',category='error')
		else:
			message = 'Account created succesfully'
			# new_user = User(email=email, username=username, password=generate_password_hash(password, method='sha256'))
			new_user = User(email=email, username=username, password=generate_password_hash(password))
			db.session.add(new_user)	#add new user to database
			db.session.commit()	#commit and save changes made
			flash(message, category='success')
			login_user(new_user) 
			return redirect(url_for('views.home'))

	return render_template('signup.html', user=current_user)

@auth.route('logout')
@login_required		#ensure only logged in users accs this
def logout():
	logout_user()
	return redirect(url_for('auth.login'))	#redirect to login page


# define and protect the admin route
@auth.route('admin')
@login_required
def admin():
	return 'Admin Page'

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Note
from . import db


views = Blueprint('views', __name__)


@views.route('', methods=['GET', 'POST'])
@login_required
def home():
	if request.method == 'POST':
		note = request.form.get('note')
		if len(note) < 3:
			message = 'Your note is too short'
			flash(message, category='error')
		else:
			message = 'Your note has been added'
			flash(message, category='success')
			new_note = Note(data=note, user_id=current_user.id)
			db.session.add(new_note)
			db.session.commit()

	return render_template ('home.html', user=current_user)

@views.route('/delete-note', methods=['POST'])
def delete_note():
	note = json.loads(request.data)
	noteId = note['noteId']
	note = Note.query.get(noteId)
	if note:
		if note.user_id == current_user.id:
			db.session.delete(note)
			db.session.commit()
			return jsonify

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} Snow {% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="static/bootstrap.min.css"/>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" >
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbar">
			<div class="navbar-nav">
				{% if user.is_authenticated %}
				<a class="nav-item nav-link" id="home" href="{{url_for('views.home')}}"> Home </a> 
				<a class="nav-item nav-link" id="logout" href="{{url_for('auth.logout')}}"> Logout </a> 
				{% else %}
				<a class="nav-item nav-link" id="signup" href="{{url_for('auth.signup')}}"> Signup </a> 
				<a class="nav-item nav-link" id="login" href="{{url_for('auth.login')}}"> Login </a> 
				{% endif %}
			</div>			
		</div>
	</nav>
	{% with messages=get_flashed_messages(with_categories=true) %}
	{% if messages %}
		{% for category, message in messages %}
		{% if category == 'error' %}
			<div class="alert alert-danger alert-dismissable fade show" role="alert">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert">
					<span aria-hidden="true"> &times; </span>
				</button>
			</div>
		{% elif category == 'success' %}
			<div class="alert alert-success alert-dismissable fade show" role="alert">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert">
					<span aria-hidden="true"> &times; </span>
				</button>
			</div>
		{% endif %}
		{% endfor %}
	{% endif %}
	{% endwith %}
	<div class="container">
		{% block body %}

		{% endblock %}
		
	</div>
	<!-- <script type="text/javascript" src="static/bootstrap.min.js"></script> -->
	<script type="text/javascript" src="{{url_for('static', filename='bootstrap.min.js')}}"></script>
	<script type="text/javascript" src="{{url_for('static', filename='index.js')}}"></script>

</body>
</html>

website/templates/home.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block body %}
<h1 align="center"> Notes </h1>
	<ul class="list-group list-group-flush" id="notes">
		{% for note in user.notes %}
			<li class="list-item-group"> {{ note.data }}
			<button type="button" class="close" onClick="deleteNote({{ note.id }})"> 
				<span aria-hidden="true"> &times; </span>
			</button>
			 </li>
		{% endfor %}
		
	</ul>

<form method="POST">
	<textarea class="form-control" id="note" name="note"></textarea>
	<br/>
	<div align="center">
		<button type="submit" class="btn btn-primary"> Add Note </button>
	</div>
</form>

{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block body %}


<form method="POST">
	<fieldset> <h1 align="center"> Login </h1>
		<div class="form-group">
			<label for="email"> Email Address </label>
			<input type="email" id="email" name="email" class="form-control" placeholder="Enter Email" autofocus />
		</div>
		<!-- learn how they put username/email in login pages -->
		<!-- <div class="form-group">
			<label for="username"> Username </label>
			<input type="text" id="username" name="username" class="form-control" placeholder="Username"/>
		</div> -->
		<div class="form-group">
			<label for="password"> Password </label>
			<input type="password" id="password" name="password" class="form-control" placeholder="Enter Password"/>
		</div>
		<br/>
		<div>
			<button type="submit" class="btn btn-primary"> Login </button>
			<!-- <button type="submit" class="btn btn-secondary"> Login </button> -->
		</div>


	</fieldset>
</form>

{% endblock %}

website/templates/logout.html
{% extends "base.html" %}

{% block title %} Logout {% endblock %}


{% block body %}
{% endblock %}

website/templates/signup.html
{% extends "base.html" %}

{% block title %} Signup {% endblock %}

{% block body %}


<form method="POST">
	<fieldset> <h1 align="center"> Signup </h1>
		<div class="form-group">
			<label for="email"> Email Address </label>
			<input type="email" id="email" name="email" class="form-control" placeholder="Enter Email" autofocus />
		</div>
		<div class="form-group">
			<label for="username"> Username </label>
			<input type="text" id="username" name="username" class="form-control" placeholder="Username"/>
		</div>
		<div class="form-group">
			<label for="password"> Password </label>
			<input type="password" id="password" name="password" class="form-control" placeholder="Enter Password"/>
		</div>
		<div class="form-group">
			<label for="password2"> Confirm Password </label>
			<input type="password" id="password2" name="password2" class="form-control" placeholder="Confirm Password"/>
		</div>
		<br/>
		<div>
			<button type="submit" class="btn btn-primary"> Signup </button>
			<!-- <button type="submit" class="btn btn-secondary"> Login </button> -->
		</div>


	</fieldset>
</form>

{% endblock %}